target_column: 'price'
splitting:
  test_size: 0.2
  random_state: 42
  stratify: False
  temporal_split: False
  chunksize: 50000  # Process in chunks of 50k rows if memory constrained
paths:
  input_data: 'data/processed/cleaned_data.csv'
  output_dir: 'data/splits/'
required_columns:
  - 'year'
  - 'price'
  - 'kilometrage'