input_data: "data/splits/X_train.csv"  # Features
target_column: "price"  # Target variable
output_dir: "models/"  # Where to save models

# Global training settings
random_state: 42
n_jobs: -1  # Use all cores

cross_validation:
  cv_folds: 5
  scoring: "neg_root_mean_squared_error"

# Model configurations
models:
  random_forest:
    n_estimators: 200
    max_depth: 15
    min_samples_leaf: 3
    max_features: "sqrt"
    
  xgboost:
    n_estimators: 150
    learning_rate: 0.1
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8
    
  ridge:
    alpha: 1.0
    fit_intercept: True
    
  decision_tree:
    max_depth: 10
    min_samples_split: 5